apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::824333137275:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-CkkAztUenWW3
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
    mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::824333137275:user/devops
      username: devops
kind: ConfigMap
metadata:
  creationTimestamp: "2026-03-28T01:03:44Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1163"
  uid: 2804347b-d13c-47ad-89c7-059feefef4b9
